# Generated by Django 4.2.5 on 2023-09-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomartapp', '0003_product_brand_product_category_product_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
