# Generated by Django 4.2.5 on 2023-09-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomartapp', '0006_rename_img_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('BLACK', 'BLACK'), ('WHITE', 'WHITE'), ('NEON', 'NEON'), ('RED', 'RED'), ('BLUE', 'BLUE'), ('BROWN', 'BROWN'), ('YELLOW', 'YELLOW'), ('GREY', 'GREY'), ('PINK', 'PINK'), ('GREEN', 'GREEN'), ('ORANGE', 'ORANGE'), ('PURPLE', 'PURPLE'), ('N', 'NONE')], default='N', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('SHIRT', 'BLACK'), ('TROUSER', 'WHITE'), ('SHORTS', 'NEON'), ('SNEAKER', 'RED'), ('BLUE', 'BLUE'), ('BROWN', 'BROWN'), ('YELLOW', 'YELLOW'), ('GREY', 'GREY'), ('PINK', 'PINK'), ('GREEN', 'GREEN'), ('ORANGE', 'ORANGE'), ('PURPLE', 'PURPLE'), ('N', 'NONE')], default='N', max_length=20),
        ),
    ]
