# Generated by Django 4.2.5 on 2023-09-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gomartapp', '0010_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
