# Generated by Django 4.2.5 on 2023-09-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomartapp', '0011_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Gucci', 'Gucci'), ('Nike', 'Nike'), ('Hublot', 'Hublot'), ('Northface', 'Northface'), ('Ellesse', 'Ellesse'), ('Balenciaga', 'Balenciaga'), ('vincero', 'vincero'), ('Vinchigo', 'Vinchigo'), ('Tommy Hilfiger', 'Tommy Hilfiger'), ('Jersy', 'Jersy'), ('Converse', 'Converse'), ('Reebok', 'Reebok'), ('Adidas', 'Adidas'), ('Puma', 'Puma'), ('Drm', 'Drm'), ('Keppa', 'Keppa'), ('Palace', 'Palace'), ('Converse', 'Converse'), ('Metalica', 'Metalica'), ('Under', 'Under'), ('N', 'None')], default='N', max_length=20),
        ),
    ]
