# Generated by Django 4.2.5 on 2023-09-24 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gomartapp', '0012_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('SHIRT', 'SHIRT'), ('TROUSER', 'TROUSER'), ('SHORTS', 'SHORTS'), ('SNEAKER', 'SNEAKER'), ('CAP', 'CAP'), ('HOODIE', 'HOODIE'), ('TSHIRT', 'TSHIRT'), ('JERSEY', 'JERSEY'), ('CAP', 'CAP'), ('BELT', 'BELT'), ('SOCKS', 'SOCKS'), ('WATCHES', 'WATCHES'), ('BAGS', 'BAGS'), ('N', 'NONE')], default='N', max_length=20),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
