# Generated by Django 4.2.6 on 2023-10-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomartapp', '0019_alter_cartitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_name',
            field=models.CharField(default='nike pink', max_length=255),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='username',
            field=models.CharField(default='tomi', max_length=150),
        ),
    ]
