# Generated by Django 4.2.6 on 2023-10-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomartapp', '0030_alter_cartitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartuser', models.CharField(default='Tomi', max_length=100)),
                ('cartItems', models.CharField(default='Ellesse', max_length=100)),
                ('totalAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
