# Generated by Django 4.2.6 on 2023-10-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomartapp', '0032_checkout_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='cartItems',
            field=models.CharField(default='Ellesse', max_length=10000),
        ),
    ]
