# Generated by Django 4.2.6 on 2023-10-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomartapp', '0034_remove_checkout_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=100),
        ),
    ]
