# Generated by Django 4.2.6 on 2023-10-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomartapp', '0035_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selectedSize',
            field=models.CharField(default='N', max_length=100),
        ),
    ]
