# Generated by Django 4.2.6 on 2023-10-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomartapp', '0037_rename_quantity_cartitem_quantity2'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='ratingValue',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100),
        ),
    ]
