# Generated by Django 4.2.6 on 2023-10-24 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gomartapp', '0039_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lastname',
        ),
    ]
