# Generated by Django 4.2.6 on 2023-10-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gomartapp', '0042_alaye'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alaye',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Alaye',
        ),
    ]
