# Generated by Django 4.2.6 on 2023-10-25 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gomartapp', '0043_remove_alaye_user_delete_profile_delete_alaye'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customeruser', models.CharField(default='Tomi', max_length=100)),
                ('phone_number', models.CharField(default='Ellesse', max_length=100)),
                ('city', models.CharField(default='lagos', max_length=100)),
                ('customerimage', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
