# Generated by Django 4.2.6 on 2023-10-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomartapp', '0045_remove_customer_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='lagos', max_length=100),
        ),
    ]
