# Generated by Django 4.2.6 on 2023-10-25 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gomartapp', '0046_customer_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
