# Generated by Django 4.2.6 on 2023-10-25 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gomartapp', '0050_remove_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lastname',
        ),
    ]
