# Generated by Django 4.2.6 on 2023-10-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomartapp', '0051_remove_customer_firstname_remove_customer_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerimage',
            field=models.ImageField(blank=True, null=True, upload_to='gomartfiles/static/'),
        ),
    ]
