# Generated by Django 4.2.6 on 2023-10-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomartapp', '0052_alter_customer_customerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerimage',
            field=models.ImageField(blank=True, null=True, upload_to='gomartfiles/static/profile_pictures'),
        ),
    ]
